### ISSUE TITLE
Is there a way to analyse only the application code and ignore the library?

### ISSUE THREAD

**Issue by rayobanon** [plast-lab/doop-pldi15-tutorial#1]
Presently Doop performs a whole program analysis and the library will be analyzed along with application code. 

Is there a way to analyse only the application code and ignore the library?

**Comment by anantoni** [comment]
You could try the flag --Xfacts-subet APP_N_DEPS. This will only generate facts for the app itself and its dependencies, so the analysis will only be performed on that part of the program.

**Comment by yanniss** [comment]
I would also recommend trying the less invasive flag --exclude-implicitly-reachable-code. This won't ignore the library, but it will only include the parts of the library explicitly reachable from "main". I.e., it won't worry about threads and threadgroups and other such functionality that the JVM specification requires that it be initialized.

**Comment by rayobanon** [comment]
Thanks. It fulfilled my requirement.
